User.create(name: "Franco", email: "franco@franco.franco", password: "password", password_confirmation: "password")
Expense.create(category: "Coffee", budget: 50, user_id: 1)
Expense.create(category: "Food", budget: 50, user_id: 1)
Transaction.create(expense_id: 1, user_id: 1, name: "Starbucks", value: 4.50, day: "01/01/2017")
Transaction.create(expense_id: 1, user_id: 1, name: "Dunkin Donuts", value: 3.25, day: "01/01/2017")
Transaction.create(expense_id: 1, user_id: 1, name: "Essen", value: 8.75, day: "01/01/2017")
Transaction.create(expense_id: 1, user_id: 1, name: "Dig Inn", value: 12.25, day: "01/01/2017")
Goal.create(name: "Vacation", budget: 1000, user_id: 1)
Income.create(name: "Flatiron Engineer", amount: 5000, user_id: 1)
Saving.create(name: "Corporate Bank", budget: 3000, user_id: 1)
#Expense_Transaction.create(transaction_id: Transaction.first, expense_id: Expense.first)
